name: MySQL Shell Installation

on:
  push:
    branches:
      - master

jobs:
  install-mysql-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Extract MySQL Shell
        run: |
          # Download MySQL Shell zip archive
          wget https://dev.mysql.com/downloads/gpg/?file=mysql-shell_8.0.34-1ubuntu23.04_amd64.deb&p=43
          sudo dpkg -i mysql-shell_8.0.34-1ubuntu23.04_amd64.deb

          # Create a directory to extract MySQL Shell
          sudo mkdir -p /opt/mysql-shell

          # Extract the zip archive
          sudo unzip -d /opt/mysql-shell mysql-shell_8.0.34-1ubuntu23.04_amd64.deb
          mysqlsh --version
