name: Install and run mysqlsh --version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Add MySQL APT Repository
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8C718D3B5072E1F5
          echo "deb http://repo.mysql.com/apt/ubuntu/ $(lsb_release -cs) mysql-tools main" | sudo tee /etc/apt/sources.list.d/mysql-tools.list
          sudo apt-get update
      - name: Set up MySQL Shell Runner
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client
          sudo apt-get install mysql-shell
       
      - name: Execute SQL Script
        run: |
          mysqlsh -u root  -p root --file=path/to/your/sql/script.sql
          mysqlsh --version
      
      - name: Install jq
        run: |
          # Install jq 1.6
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
          chmod +x jq
          sudo mv jq /usr/local/bin/jq
          # Check the installed version
          jq --version
      - name: Install gcloud
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          gcloud --version
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
