name: Install and run mysqlsh --version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install MySQL Shell
        run: |
         wget https://dev.mysql.com/get/mysql-utilities/mysql-shell-8.0.25/mysql-shell-8.0.25-linux-glibc2.12-x86-64bit.dbru -O mysql-shell.dbru
         sudo mysqlsh --install mysql-shell.dbru
         echo "PATH=$Path"
         mysqlsh --version
      - name: Run mysqlsh --version
        run: mysqlsh --version
