name: Install and run mysqlsh --version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install mysqlsh
        run: sudo apt install -y mysqlsh

      - name: Run mysqlsh --version
        run: mysqlsh --version
