name: MySQL Shell Installation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install MySQL Shell
      run: |
        sudo apt update
        sudo apt install -y mysql-shell

    - name: Verify MySQL Shell Installation
      run: |
        mysqlsh --version
