name: SQL*Plus Workflow

on:
  push:
    branches:
      - master  # Modify this branch name as needed

jobs:
  sqlplus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install SQL*Plus
      run: |
        sudo apt-get update
        sudo apt-get install -y libaio1
        # Download and install Oracle Instant Client and SQL*Plus
        wget https://download.oracle.com/otn_software/linux/instantclient/213000/instantclient-basic-linux.x64-21.3.0.0.0.zip
        unzip instantclient-basic-linux.x64-21.3.0.0.0.zip -d /opt/oracle/
        export LD_LIBRARY_PATH="/opt/oracle/instantclient_21_3:$LD_LIBRARY_PATH"
        sudo ln -s /opt/oracle/instantclient_21_3/sqlplus /usr/local/bin/sqlplus

    - name: Run SQL*Plus Script
      run: |
        # You can use sqlplus here with your credentials to connect to the database
        sqlplus username/password@//hostname:port/service_name <<EOF
        SELECT * FROM your_table;
        exit;
        EOF
