name: MySQL Shell Installation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install MySQL Shell
      run: |
        sudo apt update
        sudo snap install mysql-shell
       

   
