name: MySQL Shell Installation

on:
  push:
    branches:
      - master

jobs:
  install-mysql-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL Shell
        run: |
          # Download MySQL Shell
          wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.27-linux-glibc2.12-x86-64bit.tar.gz
          
          # Extract MySQL Shell
          tar -xzvf mysql-shell-8.0.27-linux-glibc2.12-x86-64bit.tar.gz
          
          # Install MySQL Shell (move to a suitable location)
          mv mysql-shell-8.0.27-linux-glibc2.12-x86-64bit /usr/local/mysql-shell
          
          # Add MySQL Shell to PATH
          echo 'export PATH=$PATH:/usr/local/mysql-shell/bin' >> $HOME/.bashrc
          source $HOME/.bashrc
        shell: bash
