name: MySQL Shell Installation

on:
  push:
    branches:
      - master

jobs:
  install-mysql-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Extract MySQL Shell
        run: |
          # Download MySQL Shell zip archive
          wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.27-linux-glibc2.12-x86-64bit.zip -O mysql-shell.zip

          # Create a directory to extract MySQL Shell
          mkdir -p mysql-shell

          # Extract the zip archive
          unzip mysql-shell.zip -d mysql-shell
          mysqlsh --version
        shell: bash
