name: MySQL Shell Installation and Version Check

on:
  push:
    branches:
      - master

jobs:
  install-mysql-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL Shell
        run: |
          # Download and install MySQL Shell
          wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.27-linux-glibc2.12-x86-64bit.tar.gz
          tar -xzvf mysql-shell-8.0.27-linux-glibc2.12-x86-64bit.tar.gz
          export PATH=$PATH:$(root)/mysql-shell-8.0.27-linux-glibc2.12-x86-64bit/bin
          export PATH=$PATH:/mysql-shell-8.0.27-linux-glibc2.12-x86-64bit/bin
          mysqlsh --version
        shell: bash

      
