name: Run Shell Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Oracle Instant Client
      run: |
        sudo apt-get update
        sudo apt-get install -y libaio1
        mkdir instantclient
        cd instantclient
        wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
        wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
        unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
        unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
        sudo sh -c "echo /path/to/your/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf"
        sudo ldconfig
        sqlplus -V

    - name: Run Shell Script
      run: |
        chmod +x script.sh
        ./script.sh
